# These are supported funding model platforms

github: [JoSuzuki]
patreon:
open_collective: # Replace with a single Open Collective username
ko_fi: # Don know
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
